services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: dashdina-app
    container_name: dashdina-app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
    networks:
      dashdina-network:
        ipv4_address: 172.25.0.2
    env_file: .env

  nginx:
    image: nginx:alpine
    container_name: dashdina-nginx
    restart: unless-stopped
    ports:
      - "3000:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      dashdina-network:
        ipv4_address: 172.25.0.3
    depends_on:
      - app

networks:
  dashdina-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.25.0.0/16
          gateway: 172.25.0.1
