services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: dashdina-app
    container_name: dashdina-app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
    networks:
      - dashdina-network
    env_file: .env

  nginx:
    image: nginx:alpine
    container_name: dashdina-nginx
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - dashdina-network
    depends_on:
      - app

networks:
  dashdina-network:
    driver: bridge
